name: coin_tracker
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_database: ^10.0.9
  http: ^0.13.4
  flutter_local_notifications: ^13.0.0
  flutter_background_service: ^2.1.3
  device_info_plus: ^8.0.0
  flutter_riverpod: ^2.1.3
  equatable: ^2.0.5
  fl_chart: ^0.55.2
  shared_preferences: ^2.0.16
  

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
